# Generated by Django 5.2.8 on 2025-11-11 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoneti', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
