# Generated by Django 5.2.8 on 2025-11-12 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoneti', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMilkDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('total_milk', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leftover_milk', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('leftover_sales', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'systemmilkdistribution',
            },
        ),
    ]
