# Generated by Django 5.2.8 on 2025-11-12 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoneti', '0002_user_last_login_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='manager_id',
            field=models.CharField(blank=True, editable=False, max_length=10, primary_key=True, serialize=False, unique=True),
        ),
    ]
