# Generated by Django 5.2.8 on 2025-11-12 17:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoneti', '0002_systemmilkdistribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='milkreceived',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='milk_distributed', to='Thoneti.manager'),
        ),
        migrations.AddField(
            model_name='milkreceived',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('not_received', 'Not Received')], default='pending', max_length=20),
        ),
    ]
