# Generated by Django 5.2.8 on 2025-11-13 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Thoneti', '0003_milkreceived_manager_milkreceived_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dailytotal',
            old_name='total_received',
            new_name='cash_sales',
        ),
        migrations.RenameField(
            model_name='dailytotal',
            old_name='total_sold',
            new_name='online_sales',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
