from django.urls import path
from . import views

urlpatterns = [
    path('', views.LoginPageView.as_view(), name='login-page'),
    path('admin/', views.AdminDashboardView.as_view(), name='admin-dashboard'),
    path('manager/', views.ManagerDashboardView.as_view(), name='manager-dashboard'),
    path('employee/', views.EmployeeDashboardView.as_view(), name='employee-dashboard'),
    path('seller/', views.SellerDashboardView.as_view(), name='seller-dashboard'),


    path('api/login/', views.login_view, name='api-login'),
    path('api/logout/', views.logout_view, name='api-logout'),
    path('api/manager/feed/', views.create_feed_record, name='create-feed-record'),
    path('api/manager/expense/', views.create_expense_record, name='create-expense-record'),
    path('api/misc-expenses/', views.create_misc_expense_record, name='misc-expenses'),
    path('api/manager/medicine/', views.create_medicine_record, name='create-medicine-record'),
    path('api/manager/milk-distribution/', views.record_milk_distribution, name='record-milk-distribution'),
    path('api/manager/leftover-milk/', views.update_leftover_milk, name='update-leftover-milk'),
    path('api/manager/employees/add/', views.add_employee, name='add-employee'),
    path('api/manager/employees/', views.list_employees, name='list-employees'),
    path('api/manager/attendance/', views.mark_attendance, name='mark-attendance'),
    path('api/manager/deductions/', views.create_deduction, name='create-deduction'),
    path('api/manager/location-seller/', views.add_location_seller, name='add-location-seller'),
    path('api/manager/sellers/add/', views.add_seller, name='add-seller'),
    path('api/manager/locations/', views.list_locations, name='list-locations'),
    path('api/manager/sellers/', views.list_sellers, name='list-sellers'),
    path('api/employee/dashboard/', views.employee_dashboard, name='employee-dashboard'),
    path('api/employee/attendance/', views.get_employee_attendance, name='get-employee-attendance'),
    path('api/seller/milk-received/', views.record_milk_received, name='record-milk-received'),
    path('api/seller/sales/', views.record_daily_sales, name='record-daily-sales'),
    path('api/seller/summary/', views.seller_daily_summary, name='seller-daily-summary'),
    path('api/seller/milk-request/create/', views.create_milk_request, name='create-milk-request'),
    path('api/seller/milk-request/<uuid:request_id>/accept/', views.accept_milk_request, name='accept-milk-request'),
    path('api/seller/milk-request/<uuid:request_id>/received/', views.mark_as_received, name='mark-as-received'),
    path('api/seller/milk-requests/incoming/', views.list_incoming_requests, name='list-incoming-requests'),
    path('api/manager/dashboard-stats/', views.manager_dashboard_stats, name='manager-dashboard-stats'),
    path('api/seller/milk-requests/mine/', views.list_my_requests, name='list-my-requests'),
    path('api/notifications/', views.list_notifications, name='list-notifications'),
    path('api/notifications/<uuid:notification_id>/read/', views.mark_notification_read, name='mark-notification-read'),
    path('api/seller/borrow-lend-history/', views.get_borrow_lend_history, name='borrow-lend-history'),
    path('api/manager/datewise-data/', views.get_datewise_data, name='get-datewise-data'),
    path('api/manager/daily-data/', views.get_daily_data, name='get-daily-data'),
    path('api/admin/managers/add/', views.add_manager, name='add-manager'),
    path('api/admin/managers/', views.list_managers, name='list-managers'),
    path('api/admin/managers/<str:manager_id>/delete/', views.delete_manager, name='delete-manager'),
]
